## Task 1
### Напишіть функцію, яка приймає довільну матрицю і повертає три матриці використовуючи бібліотеку NumPy

In [4]:
## SVD realization
import numpy as np

def svd(matrix):

    # 1) Find symmetric marix 2x2 and 3x3
    # (2x2 - U matrix, 3x3T - VT matrix)

    # MATRIX 2x2
    mul_MT_M = np.dot(matrix.T, matrix)

    #matrix 3x3
    mul_M_MT = np.dot(matrix, matrix.T)

    # 2)
    # Find Eigen Values and Vectors
    eigenval_MT_M, eigenvec_MT_M = np.linalg.eigh(mul_MT_M)
    eigenval_M_MT, eigenvec_M_MT = np.linalg.eigh(mul_M_MT)

    # sort it in descending order
    desc_ind_MT_M = np.argsort(eigenval_MT_M)[::-1]
    desc_ind_M_MT = np.argsort(eigenval_M_MT)[::-1]

    eigenval_MT_M = eigenval_MT_M[desc_ind_MT_M]
    eigenval_M_MT = eigenval_M_MT[desc_ind_M_MT]

    eigenvec_MT_M = eigenvec_MT_M[:, desc_ind_MT_M]
    eigenvec_M_MT = eigenvec_M_MT[:, desc_ind_M_MT]


    # 3) Sigma Matrix

    sigma = np.sqrt(eigenval_MT_M)
    sigma_matrix = np.zeros_like(matrix, dtype=float)
    np.fill_diagonal(sigma_matrix, sigma)

    # 4) CHECK for recostruct
    reconstructed_matrix = np.dot(eigenvec_M_MT, np.dot(sigma_matrix, eigenvec_MT_M.T))
    is_reconstructed = np.allclose(matrix, reconstructed_matrix)

    return eigenvec_MT_M, sigma_matrix, eigenvec_M_MT, is_reconstructed



matrix = np.array([
    [3, 2],
    [2, 3],
    [2, -2]
])
names = ["U matrix\n", "Sigma Matrix\n", "Vt Matrix\n", "Is reconstructed: "]

result = svd(matrix)
for name, el in zip(names, result):
    print(name, el)
    print('\n\n')

U matrix
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]



Sigma Matrix
 [[5. 0.]
 [0. 3.]
 [0. 0.]]



Vt Matrix
 [[-7.07106781e-01  2.35702260e-01 -6.66666667e-01]
 [-7.07106781e-01 -2.35702260e-01  6.66666667e-01]
 [-6.93889390e-17  9.42809042e-01  3.33333333e-01]]



Is reconstructed:  False
